### ISSUE TITLE
nan output

### ISSUE THREAD

**Issue by briannlongzhao** [wster/conditional-vdvae#1]
Hi, I was trying to run the sample.py with your pretrained weights but got all black images, the output of the decoder is all nan, what might be the problem? Thanks!

**Comment by augustwester** [comment]
Hi! It's been quite a while since I looked at this code 😅 I was, however, able to reproduce the problem and have pushed a fix. Let me know if it works for you.

**Comment by briannlongzhao** [comment]
That worked, thank you so much for the help!
